name: Package

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:

  wheel-linux-aarch64:
    name: Build Linux wheels (Aarch64)
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        python-tag:
        - cp38-manylinux_aarch64
        - cp39-manylinux_aarch64
        - cp310-manylinux_aarch64
        - cp311-manylinux_aarch64
        - cp312-manylinux_aarch64
        - cp313-manylinux_aarch64
        - cp314-manylinux_aarch64
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
        fetch-depth: 0
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v3.4.1
      env:
        CIBW_ARCHS: aarch64
        CIBW_BUILD: ${{ matrix.python-tag }}
        CIBW_BUILD_VERBOSITY: 2
        CIBW_MANYLINUX_AARCH64_IMAGE: quay.io/pypa/manylinux2014_aarch64:2026.04.24-1
        CIBW_BEFORE_BUILD: pip install cython pytest
        CIBW_TEST_COMMAND: "pytest --import-mode=importlib {project}/tests/"
        CIBW_TEST_REQUIRES: pytest
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.python-tag }}
        path: dist/*

  wheel-linux-x86_64:
    name: Build Linux wheels (x86-64)
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-tag:
        - cp38-manylinux_x86_64
        - cp39-manylinux_x86_64
        - cp310-manylinux_x86_64
        - cp311-manylinux_x86_64
        - cp312-manylinux_x86_64
        - cp313-manylinux_x86_64
        - cp314-manylinux_x86_64
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
        fetch-depth: 0
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v3.4.1
      env:
        CIBW_ARCHS: x86_64
        CIBW_BUILD: ${{ matrix.python-tag }}
        CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux2014_x86_64:2026.04.24-1
        CIBW_BEFORE_BUILD: pip install cython pytest
        CIBW_BUILD_VERBOSITY: 2
        CIBW_BEFORE_TEST: "git status && ls -lh"
        CIBW_TEST_COMMAND: "pytest --import-mode=importlib {project}/tests/"
        CIBW_TEST_REQUIRES: pytest
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.python-tag }}
        path: dist/*

  wheel-macos-aarch64-m14:
    name: Build MacOS wheels (Aarch64, macos-14)
    runs-on: macos-14
    strategy:
      matrix:
        python-tag:
        - cp310-macosx_arm64
        - cp311-macosx_arm64
        - cp312-macosx_arm64
        - cp313-macosx_arm64
        - cp314-macosx_arm64
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: true
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v3.4.1
      env:
        CIBW_ARCHS: arm64
        CIBW_BUILD: ${{ matrix.python-tag }}
        CIBW_BEFORE_BUILD: pip install cython pytest
        CIBW_BUILD_VERBOSITY: 2
        CIBW_TEST_COMMAND: "pytest --import-mode=importlib {project}/tests/"
        CIBW_TEST_REQUIRES: pytest
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.python-tag }}
        path: dist/*

  wheel-win32-x86_64:
    name: Build Windows wheels (x86-64)
    runs-on: windows-2022
    strategy:
      matrix:
        python-tag:
        - cp38-win_amd64
        - cp39-win_amd64
        - cp310-win_amd64
        - cp311-win_amd64
        - cp312-win_amd64
        - cp313-win_amd64
        - cp314-win_amd64
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
        fetch-depth: 0
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v3.4.1
      env:
        CIBW_ARCHS: AMD64
        CIBW_BUILD: ${{ matrix.python-tag }}
        CIBW_BEFORE_BUILD: pip install cython pytest
        CIBW_BUILD_VERBOSITY: 2
        CIBW_TEST_COMMAND: "pytest --import-mode=importlib {project}/tests/"
        CIBW_TEST_REQUIRES: pytest
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.python-tag }}
        path: dist/*

  sdist:
    runs-on: ubuntu-24.04
    name: Build source distribution
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
        fetch-depth: 0
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: 3.12
    - name: Install build requirements
      run: python -m pip install -r ./requirements.txt setuptools
    - name: Build source distribution
      run: python setup.py sdist
    - name: Store built source distribution
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*

  test-sdist:
    runs-on: ubuntu-24.04
    name: Test source distribution
    needs:
    - sdist
    steps:
    - name: Setup Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - name: Download built sdist
      uses: actions/download-artifact@v4
      with:
          name: sdist
          path: dist/
    - name: Update pip to latest version
      run: python -m pip install -U pip setuptools wheel pytest
    - name: Install built wheel
      run: python -m pip install --pre dist/*.tar.gz
    - name: Extract tests from sdist
      run: tar xzvf dist/*.tar.gz && cp -r fisher-*/tests/ . && rm -r fisher-*
    - name: Run tests
      run: pytest tests/

  upload:
    environment: PyPI
    runs-on: ubuntu-24.04
    name: Upload
    permissions:
      id-token: write
    needs:
    - sdist
    - test-sdist
    - wheel-linux-aarch64
    - wheel-linux-x86_64
    - wheel-macos-aarch64-m14
    - wheel-win32-x86_64
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: wheels-*
        merge-multiple: true
        path: dist
    - uses: actions/download-artifact@v4
      with:
        name: sdist
        path: dist
    - uses: pypa/gh-action-pypi-publish@release/v1
      if: startsWith(github.ref, 'refs/tags')
      with:
        skip-existing: true
